services:
  frontend:
    build:
      context: ./mobile-app
    image: mern/frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: mern/backend
    network_mode: host
    volumes:
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
